// @generated
// This file is @generated by prost-build.
/// StringFilter matches the value of a string against a set of rules.
/// All of the non-zero rules must match for the filter to match.
/// An empty filter matches any.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StringFilter {
    /// Empty matches the value against the empty value.
    #[prost(bool, tag="1")]
    pub empty: bool,
    /// NotEmpty matches the value against a not-empty value.
    #[prost(bool, tag="2")]
    pub not_empty: bool,
    /// Value matches an exact value.
    #[prost(string, tag="3")]
    pub value: ::prost::alloc::string::String,
    /// Values matches one or more exact values.
    /// If any of the values match, this field is considered matched.
    #[prost(string, repeated, tag="4")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Re matches the value against a regular expression.
    #[prost(string, tag="5")]
    pub re: ::prost::alloc::string::String,
    /// HasPrefix checks if the value has the given prefix.
    #[prost(string, tag="6")]
    pub has_prefix: ::prost::alloc::string::String,
    /// HasSuffix checks if the value has the given suffix.
    #[prost(string, tag="7")]
    pub has_suffix: ::prost::alloc::string::String,
    /// Contains checks if the value contains the given value.
    #[prost(string, tag="8")]
    pub contains: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
