//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/util/filter/filter.proto
// Protobuf C++ Version: 6.33.4

#ifndef github_2ecom_2faperturerobotics_2futil_2ffilter_2ffilter_2eproto_2epb_2eh
#define github_2ecom_2faperturerobotics_2futil_2ffilter_2ffilter_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_github_2ecom_2faperturerobotics_2futil_2ffilter_2ffilter_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_github_2ecom_2faperturerobotics_2futil_2ffilter_2ffilter_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2futil_2ffilter_2ffilter_2eproto;
}  // extern "C"
namespace filter {
class StringFilter;
struct StringFilterDefaultTypeInternal;
extern StringFilterDefaultTypeInternal _StringFilter_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull StringFilter_class_data_;
}  // namespace filter
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace filter {

// ===================================================================


// -------------------------------------------------------------------

class StringFilter final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:filter.StringFilter) */ {
 public:
  inline StringFilter() : StringFilter(nullptr) {}
  ~StringFilter() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(StringFilter* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(StringFilter));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StringFilter(::google::protobuf::internal::ConstantInitialized);

  inline StringFilter(const StringFilter& from) : StringFilter(nullptr, from) {}
  inline StringFilter(StringFilter&& from) noexcept
      : StringFilter(nullptr, ::std::move(from)) {}
  inline StringFilter& operator=(const StringFilter& from) {
    CopyFrom(from);
    return *this;
  }
  inline StringFilter& operator=(StringFilter&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StringFilter& default_instance() {
    return *reinterpret_cast<const StringFilter*>(
        &_StringFilter_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(StringFilter& a, StringFilter& b) { a.Swap(&b); }
  inline void Swap(StringFilter* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StringFilter* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StringFilter* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<StringFilter>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StringFilter& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StringFilter& from) { StringFilter::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(StringFilter* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "filter.StringFilter"; }

  explicit StringFilter(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  StringFilter(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const StringFilter& from);
  StringFilter(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, StringFilter&& from) noexcept
      : StringFilter(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValuesFieldNumber = 4,
    kValueFieldNumber = 3,
    kReFieldNumber = 5,
    kHasPrefixFieldNumber = 6,
    kHasSuffixFieldNumber = 7,
    kContainsFieldNumber = 8,
    kEmptyFieldNumber = 1,
    kNotEmptyFieldNumber = 2,
  };
  // repeated string values = 4;
  int values_size() const;
  private:
  int _internal_values_size() const;

  public:
  void clear_values() ;
  const ::std::string& values(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_values(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_values(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_values();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_values(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& values() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_values();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_values() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_values();

  public:
  // string value = 3;
  void clear_value() ;
  const ::std::string& value() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_value(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_value();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_value();
  void set_allocated_value(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_value() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_value(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_value();

  public:
  // string re = 5;
  void clear_re() ;
  const ::std::string& re() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_re(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_re();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_re();
  void set_allocated_re(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_re() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_re(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_re();

  public:
  // string has_prefix = 6;
  void clear_has_prefix() ;
  const ::std::string& has_prefix() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_has_prefix(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_has_prefix();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_has_prefix();
  void set_allocated_has_prefix(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_has_prefix() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_has_prefix(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_has_prefix();

  public:
  // string has_suffix = 7;
  void clear_has_suffix() ;
  const ::std::string& has_suffix() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_has_suffix(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_has_suffix();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_has_suffix();
  void set_allocated_has_suffix(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_has_suffix() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_has_suffix(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_has_suffix();

  public:
  // string contains = 8;
  void clear_contains() ;
  const ::std::string& contains() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_contains(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_contains();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_contains();
  void set_allocated_contains(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_contains() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_contains(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_contains();

  public:
  // bool empty = 1;
  void clear_empty() ;
  bool empty() const;
  void set_empty(bool value);

  private:
  bool _internal_empty() const;
  void _internal_set_empty(bool value);

  public:
  // bool not_empty = 2;
  void clear_not_empty() ;
  bool not_empty() const;
  void set_not_empty(bool value);

  private:
  bool _internal_not_empty() const;
  void _internal_set_not_empty(bool value);

  public:
  // @@protoc_insertion_point(class_scope:filter.StringFilter)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   0, 77,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const StringFilter& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> values_;
    ::google::protobuf::internal::ArenaStringPtr value_;
    ::google::protobuf::internal::ArenaStringPtr re_;
    ::google::protobuf::internal::ArenaStringPtr has_prefix_;
    ::google::protobuf::internal::ArenaStringPtr has_suffix_;
    ::google::protobuf::internal::ArenaStringPtr contains_;
    bool empty_;
    bool not_empty_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2futil_2ffilter_2ffilter_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull StringFilter_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// StringFilter

// bool empty = 1;
inline void StringFilter::clear_empty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.empty_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline bool StringFilter::empty() const {
  // @@protoc_insertion_point(field_get:filter.StringFilter.empty)
  return _internal_empty();
}
inline void StringFilter::set_empty(bool value) {
  _internal_set_empty(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:filter.StringFilter.empty)
}
inline bool StringFilter::_internal_empty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.empty_;
}
inline void StringFilter::_internal_set_empty(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.empty_ = value;
}

// bool not_empty = 2;
inline void StringFilter::clear_not_empty() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.not_empty_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline bool StringFilter::not_empty() const {
  // @@protoc_insertion_point(field_get:filter.StringFilter.not_empty)
  return _internal_not_empty();
}
inline void StringFilter::set_not_empty(bool value) {
  _internal_set_not_empty(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:filter.StringFilter.not_empty)
}
inline bool StringFilter::_internal_not_empty() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.not_empty_;
}
inline void StringFilter::_internal_set_not_empty(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.not_empty_ = value;
}

// string value = 3;
inline void StringFilter::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& StringFilter::value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:filter.StringFilter.value)
  return _internal_value();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void StringFilter::set_value(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.value_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:filter.StringFilter.value)
}
inline ::std::string* PROTOBUF_NONNULL StringFilter::mutable_value()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:filter.StringFilter.value)
  return _s;
}
inline const ::std::string& StringFilter::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_.Get();
}
inline void StringFilter::_internal_set_value(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL StringFilter::_internal_mutable_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.value_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE StringFilter::release_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:filter.StringFilter.value)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.value_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.value_.Set("", GetArena());
  }
  return released;
}
inline void StringFilter::set_allocated_value(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.value_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:filter.StringFilter.value)
}

// repeated string values = 4;
inline int StringFilter::_internal_values_size() const {
  return _internal_values().size();
}
inline int StringFilter::values_size() const {
  return _internal_values_size();
}
inline void StringFilter::clear_values() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.values_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::std::string* PROTOBUF_NONNULL StringFilter::add_values()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_values()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add_mutable:filter.StringFilter.values)
  return _s;
}
inline const ::std::string& StringFilter::values(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:filter.StringFilter.values)
  return _internal_values().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL StringFilter::mutable_values(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:filter.StringFilter.values)
  return _internal_mutable_values()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void StringFilter::set_values(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_values()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:filter.StringFilter.values)
}
template <typename Arg_, typename... Args_>
inline void StringFilter::add_values(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_values(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:filter.StringFilter.values)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& StringFilter::values()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:filter.StringFilter.values)
  return _internal_values();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
StringFilter::mutable_values() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:filter.StringFilter.values)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_values();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
StringFilter::_internal_values() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.values_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
StringFilter::_internal_mutable_values() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.values_;
}

// string re = 5;
inline void StringFilter::clear_re() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.re_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& StringFilter::re() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:filter.StringFilter.re)
  return _internal_re();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void StringFilter::set_re(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.re_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:filter.StringFilter.re)
}
inline ::std::string* PROTOBUF_NONNULL StringFilter::mutable_re()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_re();
  // @@protoc_insertion_point(field_mutable:filter.StringFilter.re)
  return _s;
}
inline const ::std::string& StringFilter::_internal_re() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.re_.Get();
}
inline void StringFilter::_internal_set_re(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.re_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL StringFilter::_internal_mutable_re() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.re_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE StringFilter::release_re() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:filter.StringFilter.re)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.re_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.re_.Set("", GetArena());
  }
  return released;
}
inline void StringFilter::set_allocated_re(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.re_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.re_.IsDefault()) {
    _impl_.re_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:filter.StringFilter.re)
}

// string has_prefix = 6;
inline void StringFilter::clear_has_prefix() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.has_prefix_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& StringFilter::has_prefix() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:filter.StringFilter.has_prefix)
  return _internal_has_prefix();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void StringFilter::set_has_prefix(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.has_prefix_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:filter.StringFilter.has_prefix)
}
inline ::std::string* PROTOBUF_NONNULL StringFilter::mutable_has_prefix()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_has_prefix();
  // @@protoc_insertion_point(field_mutable:filter.StringFilter.has_prefix)
  return _s;
}
inline const ::std::string& StringFilter::_internal_has_prefix() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.has_prefix_.Get();
}
inline void StringFilter::_internal_set_has_prefix(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.has_prefix_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL StringFilter::_internal_mutable_has_prefix() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.has_prefix_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE StringFilter::release_has_prefix() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:filter.StringFilter.has_prefix)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.has_prefix_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.has_prefix_.Set("", GetArena());
  }
  return released;
}
inline void StringFilter::set_allocated_has_prefix(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.has_prefix_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.has_prefix_.IsDefault()) {
    _impl_.has_prefix_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:filter.StringFilter.has_prefix)
}

// string has_suffix = 7;
inline void StringFilter::clear_has_suffix() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.has_suffix_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::std::string& StringFilter::has_suffix() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:filter.StringFilter.has_suffix)
  return _internal_has_suffix();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void StringFilter::set_has_suffix(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.has_suffix_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:filter.StringFilter.has_suffix)
}
inline ::std::string* PROTOBUF_NONNULL StringFilter::mutable_has_suffix()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_has_suffix();
  // @@protoc_insertion_point(field_mutable:filter.StringFilter.has_suffix)
  return _s;
}
inline const ::std::string& StringFilter::_internal_has_suffix() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.has_suffix_.Get();
}
inline void StringFilter::_internal_set_has_suffix(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.has_suffix_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL StringFilter::_internal_mutable_has_suffix() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.has_suffix_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE StringFilter::release_has_suffix() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:filter.StringFilter.has_suffix)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.has_suffix_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.has_suffix_.Set("", GetArena());
  }
  return released;
}
inline void StringFilter::set_allocated_has_suffix(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.has_suffix_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.has_suffix_.IsDefault()) {
    _impl_.has_suffix_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:filter.StringFilter.has_suffix)
}

// string contains = 8;
inline void StringFilter::clear_contains() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.contains_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline const ::std::string& StringFilter::contains() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:filter.StringFilter.contains)
  return _internal_contains();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void StringFilter::set_contains(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  _impl_.contains_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:filter.StringFilter.contains)
}
inline ::std::string* PROTOBUF_NONNULL StringFilter::mutable_contains()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  ::std::string* _s = _internal_mutable_contains();
  // @@protoc_insertion_point(field_mutable:filter.StringFilter.contains)
  return _s;
}
inline const ::std::string& StringFilter::_internal_contains() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.contains_.Get();
}
inline void StringFilter::_internal_set_contains(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.contains_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL StringFilter::_internal_mutable_contains() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.contains_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE StringFilter::release_contains() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:filter.StringFilter.contains)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000020U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  auto* released = _impl_.contains_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.contains_.Set("", GetArena());
  }
  return released;
}
inline void StringFilter::set_allocated_contains(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  }
  _impl_.contains_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.contains_.IsDefault()) {
    _impl_.contains_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:filter.StringFilter.contains)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace filter


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // github_2ecom_2faperturerobotics_2futil_2ffilter_2ffilter_2eproto_2epb_2eh
