// @generated
// This file is @generated by prost-build.
/// Backoff configures a backoff.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Backoff {
    /// BackoffKind is the kind of backoff.
    #[prost(enumeration="BackoffKind", tag="1")]
    pub backoff_kind: i32,
    /// Exponential is the arguments for an exponential backoff.
    #[prost(message, optional, tag="2")]
    pub exponential: ::core::option::Option<Exponential>,
    /// Constant is the arugment for a constant backoff.
    #[prost(message, optional, tag="3")]
    pub constant: ::core::option::Option<Constant>,
}
/// Exponential is the exponential arguments.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Exponential {
    /// InitialInterval is the initial interval in milliseconds.
    /// Default: 800ms.
    #[prost(uint32, tag="1")]
    pub initial_interval: u32,
    /// Multiplier is the timing multiplier.
    /// Default: 1.8
    #[prost(float, tag="2")]
    pub multiplier: f32,
    /// MaxInterval is the maximum timing interval in milliseconds.
    /// Default: 20 seconds
    #[prost(uint32, tag="3")]
    pub max_interval: u32,
    /// RandomizationFactor is the randomization factor.
    /// Should be from \[0, 1\] as a percentage of the retry interval.
    ///
    /// randomized interval = RetryInterval * (random value in range \[1 - RandomizationFactor, 1 + RandomizationFactor\])
    ///
    /// Default: 0 (disabled)
    #[prost(float, tag="4")]
    pub randomization_factor: f32,
    /// MaxElapsedTime if set specifies a maximum time for the backoff, in milliseconds.
    /// After this time the backoff and attached process terminates.
    /// May be empty, might be ignored.
    #[prost(uint32, tag="5")]
    pub max_elapsed_time: u32,
}
/// Constant contains constant backoff options.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Constant {
    /// Interval is the timing to back off, in milliseconds.
    /// Defaults to 5 seconds.
    #[prost(uint32, tag="1")]
    pub interval: u32,
}
/// BackoffKind is the kind of backoff.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BackoffKind {
    /// BackoffKind_UNKNOWN defaults to BackoffKind_EXPONENTIAL
    Unknown = 0,
    /// BackoffKind_EXPONENTIAL is an exponential backoff.
    Exponential = 1,
    /// BackoffKind_CONSTANT is a constant backoff.
    Constant = 2,
}
impl BackoffKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "BackoffKind_UNKNOWN",
            Self::Exponential => "BackoffKind_EXPONENTIAL",
            Self::Constant => "BackoffKind_CONSTANT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BackoffKind_UNKNOWN" => Some(Self::Unknown),
            "BackoffKind_EXPONENTIAL" => Some(Self::Exponential),
            "BackoffKind_CONSTANT" => Some(Self::Constant),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
