//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/util/backoff/backoff.proto
// Protobuf C++ Version: 6.33.4

#ifndef github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto_2epb_2eh
#define github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto;
}  // extern "C"
namespace backoff {
enum BackoffKind : int;
extern const uint32_t BackoffKind_internal_data_[];
class Backoff;
struct BackoffDefaultTypeInternal;
extern BackoffDefaultTypeInternal _Backoff_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Backoff_class_data_;
class Constant;
struct ConstantDefaultTypeInternal;
extern ConstantDefaultTypeInternal _Constant_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Constant_class_data_;
class Exponential;
struct ExponentialDefaultTypeInternal;
extern ExponentialDefaultTypeInternal _Exponential_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Exponential_class_data_;
}  // namespace backoff
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::backoff::BackoffKind_internal_data_>
    internal::EnumTraitsImpl::value<::backoff::BackoffKind>;
}  // namespace protobuf
}  // namespace google

namespace backoff {
enum BackoffKind : int {
  BackoffKind_UNKNOWN = 0,
  BackoffKind_EXPONENTIAL = 1,
  BackoffKind_CONSTANT = 2,
  BackoffKind_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  BackoffKind_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t BackoffKind_internal_data_[];
inline constexpr BackoffKind BackoffKind_MIN =
    static_cast<BackoffKind>(0);
inline constexpr BackoffKind BackoffKind_MAX =
    static_cast<BackoffKind>(2);
inline bool BackoffKind_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int BackoffKind_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL BackoffKind_descriptor();
template <typename T>
const ::std::string& BackoffKind_Name(T value) {
  static_assert(::std::is_same<T, BackoffKind>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to BackoffKind_Name().");
  return BackoffKind_Name(static_cast<BackoffKind>(value));
}
template <>
inline const ::std::string& BackoffKind_Name(BackoffKind value) {
  return ::google::protobuf::internal::NameOfDenseEnum<BackoffKind_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool BackoffKind_Parse(
    ::absl::string_view name, BackoffKind* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<BackoffKind>(BackoffKind_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Exponential final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:backoff.Exponential) */ {
 public:
  inline Exponential() : Exponential(nullptr) {}
  ~Exponential() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Exponential* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Exponential));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Exponential(::google::protobuf::internal::ConstantInitialized);

  inline Exponential(const Exponential& from) : Exponential(nullptr, from) {}
  inline Exponential(Exponential&& from) noexcept
      : Exponential(nullptr, ::std::move(from)) {}
  inline Exponential& operator=(const Exponential& from) {
    CopyFrom(from);
    return *this;
  }
  inline Exponential& operator=(Exponential&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Exponential& default_instance() {
    return *reinterpret_cast<const Exponential*>(
        &_Exponential_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Exponential& a, Exponential& b) { a.Swap(&b); }
  inline void Swap(Exponential* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Exponential* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Exponential* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Exponential>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Exponential& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Exponential& from) { Exponential::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Exponential* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "backoff.Exponential"; }

  explicit Exponential(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Exponential(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Exponential& from);
  Exponential(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Exponential&& from) noexcept
      : Exponential(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kInitialIntervalFieldNumber = 1,
    kMultiplierFieldNumber = 2,
    kMaxIntervalFieldNumber = 3,
    kRandomizationFactorFieldNumber = 4,
    kMaxElapsedTimeFieldNumber = 5,
  };
  // uint32 initial_interval = 1;
  void clear_initial_interval() ;
  ::uint32_t initial_interval() const;
  void set_initial_interval(::uint32_t value);

  private:
  ::uint32_t _internal_initial_interval() const;
  void _internal_set_initial_interval(::uint32_t value);

  public:
  // float multiplier = 2;
  void clear_multiplier() ;
  float multiplier() const;
  void set_multiplier(float value);

  private:
  float _internal_multiplier() const;
  void _internal_set_multiplier(float value);

  public:
  // uint32 max_interval = 3;
  void clear_max_interval() ;
  ::uint32_t max_interval() const;
  void set_max_interval(::uint32_t value);

  private:
  ::uint32_t _internal_max_interval() const;
  void _internal_set_max_interval(::uint32_t value);

  public:
  // float randomization_factor = 4;
  void clear_randomization_factor() ;
  float randomization_factor() const;
  void set_randomization_factor(float value);

  private:
  float _internal_randomization_factor() const;
  void _internal_set_randomization_factor(float value);

  public:
  // uint32 max_elapsed_time = 5;
  void clear_max_elapsed_time() ;
  ::uint32_t max_elapsed_time() const;
  void set_max_elapsed_time(::uint32_t value);

  private:
  ::uint32_t _internal_max_elapsed_time() const;
  void _internal_set_max_elapsed_time(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:backoff.Exponential)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Exponential& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t initial_interval_;
    float multiplier_;
    ::uint32_t max_interval_;
    float randomization_factor_;
    ::uint32_t max_elapsed_time_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Exponential_class_data_;
// -------------------------------------------------------------------

class Constant final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:backoff.Constant) */ {
 public:
  inline Constant() : Constant(nullptr) {}
  ~Constant() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Constant* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Constant));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Constant(::google::protobuf::internal::ConstantInitialized);

  inline Constant(const Constant& from) : Constant(nullptr, from) {}
  inline Constant(Constant&& from) noexcept
      : Constant(nullptr, ::std::move(from)) {}
  inline Constant& operator=(const Constant& from) {
    CopyFrom(from);
    return *this;
  }
  inline Constant& operator=(Constant&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Constant& default_instance() {
    return *reinterpret_cast<const Constant*>(
        &_Constant_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Constant& a, Constant& b) { a.Swap(&b); }
  inline void Swap(Constant* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Constant* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Constant* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Constant>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Constant& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Constant& from) { Constant::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Constant* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "backoff.Constant"; }

  explicit Constant(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Constant(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Constant& from);
  Constant(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Constant&& from) noexcept
      : Constant(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIntervalFieldNumber = 1,
  };
  // uint32 interval = 1;
  void clear_interval() ;
  ::uint32_t interval() const;
  void set_interval(::uint32_t value);

  private:
  ::uint32_t _internal_interval() const;
  void _internal_set_interval(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:backoff.Constant)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Constant& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t interval_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Constant_class_data_;
// -------------------------------------------------------------------

class Backoff final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:backoff.Backoff) */ {
 public:
  inline Backoff() : Backoff(nullptr) {}
  ~Backoff() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Backoff* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Backoff));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Backoff(::google::protobuf::internal::ConstantInitialized);

  inline Backoff(const Backoff& from) : Backoff(nullptr, from) {}
  inline Backoff(Backoff&& from) noexcept
      : Backoff(nullptr, ::std::move(from)) {}
  inline Backoff& operator=(const Backoff& from) {
    CopyFrom(from);
    return *this;
  }
  inline Backoff& operator=(Backoff&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Backoff& default_instance() {
    return *reinterpret_cast<const Backoff*>(
        &_Backoff_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Backoff& a, Backoff& b) { a.Swap(&b); }
  inline void Swap(Backoff* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Backoff* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Backoff* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Backoff>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Backoff& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Backoff& from) { Backoff::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Backoff* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "backoff.Backoff"; }

  explicit Backoff(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Backoff(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Backoff& from);
  Backoff(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Backoff&& from) noexcept
      : Backoff(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kExponentialFieldNumber = 2,
    kConstantFieldNumber = 3,
    kBackoffKindFieldNumber = 1,
  };
  // .backoff.Exponential exponential = 2;
  bool has_exponential() const;
  void clear_exponential() ;
  const ::backoff::Exponential& exponential() const;
  [[nodiscard]] ::backoff::Exponential* PROTOBUF_NULLABLE release_exponential();
  ::backoff::Exponential* PROTOBUF_NONNULL mutable_exponential();
  void set_allocated_exponential(::backoff::Exponential* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_exponential(::backoff::Exponential* PROTOBUF_NULLABLE value);
  ::backoff::Exponential* PROTOBUF_NULLABLE unsafe_arena_release_exponential();

  private:
  const ::backoff::Exponential& _internal_exponential() const;
  ::backoff::Exponential* PROTOBUF_NONNULL _internal_mutable_exponential();

  public:
  // .backoff.Constant constant = 3;
  bool has_constant() const;
  void clear_constant() ;
  const ::backoff::Constant& constant() const;
  [[nodiscard]] ::backoff::Constant* PROTOBUF_NULLABLE release_constant();
  ::backoff::Constant* PROTOBUF_NONNULL mutable_constant();
  void set_allocated_constant(::backoff::Constant* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_constant(::backoff::Constant* PROTOBUF_NULLABLE value);
  ::backoff::Constant* PROTOBUF_NULLABLE unsafe_arena_release_constant();

  private:
  const ::backoff::Constant& _internal_constant() const;
  ::backoff::Constant* PROTOBUF_NONNULL _internal_mutable_constant();

  public:
  // .backoff.BackoffKind backoff_kind = 1;
  void clear_backoff_kind() ;
  ::backoff::BackoffKind backoff_kind() const;
  void set_backoff_kind(::backoff::BackoffKind value);

  private:
  ::backoff::BackoffKind _internal_backoff_kind() const;
  void _internal_set_backoff_kind(::backoff::BackoffKind value);

  public:
  // @@protoc_insertion_point(class_scope:backoff.Backoff)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Backoff& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::backoff::Exponential* PROTOBUF_NULLABLE exponential_;
    ::backoff::Constant* PROTOBUF_NULLABLE constant_;
    int backoff_kind_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Backoff_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Backoff

// .backoff.BackoffKind backoff_kind = 1;
inline void Backoff::clear_backoff_kind() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.backoff_kind_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::backoff::BackoffKind Backoff::backoff_kind() const {
  // @@protoc_insertion_point(field_get:backoff.Backoff.backoff_kind)
  return _internal_backoff_kind();
}
inline void Backoff::set_backoff_kind(::backoff::BackoffKind value) {
  _internal_set_backoff_kind(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:backoff.Backoff.backoff_kind)
}
inline ::backoff::BackoffKind Backoff::_internal_backoff_kind() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::backoff::BackoffKind>(_impl_.backoff_kind_);
}
inline void Backoff::_internal_set_backoff_kind(::backoff::BackoffKind value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.backoff_kind_ = value;
}

// .backoff.Exponential exponential = 2;
inline bool Backoff::has_exponential() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.exponential_ != nullptr);
  return value;
}
inline void Backoff::clear_exponential() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.exponential_ != nullptr) _impl_.exponential_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::backoff::Exponential& Backoff::_internal_exponential() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::backoff::Exponential* p = _impl_.exponential_;
  return p != nullptr ? *p : reinterpret_cast<const ::backoff::Exponential&>(::backoff::_Exponential_default_instance_);
}
inline const ::backoff::Exponential& Backoff::exponential() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:backoff.Backoff.exponential)
  return _internal_exponential();
}
inline void Backoff::unsafe_arena_set_allocated_exponential(
    ::backoff::Exponential* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.exponential_);
  }
  _impl_.exponential_ = reinterpret_cast<::backoff::Exponential*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:backoff.Backoff.exponential)
}
inline ::backoff::Exponential* PROTOBUF_NULLABLE Backoff::release_exponential() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::backoff::Exponential* released = _impl_.exponential_;
  _impl_.exponential_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::backoff::Exponential* PROTOBUF_NULLABLE Backoff::unsafe_arena_release_exponential() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:backoff.Backoff.exponential)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::backoff::Exponential* temp = _impl_.exponential_;
  _impl_.exponential_ = nullptr;
  return temp;
}
inline ::backoff::Exponential* PROTOBUF_NONNULL Backoff::_internal_mutable_exponential() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.exponential_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::backoff::Exponential>(GetArena());
    _impl_.exponential_ = reinterpret_cast<::backoff::Exponential*>(p);
  }
  return _impl_.exponential_;
}
inline ::backoff::Exponential* PROTOBUF_NONNULL Backoff::mutable_exponential()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::backoff::Exponential* _msg = _internal_mutable_exponential();
  // @@protoc_insertion_point(field_mutable:backoff.Backoff.exponential)
  return _msg;
}
inline void Backoff::set_allocated_exponential(::backoff::Exponential* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.exponential_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.exponential_ = reinterpret_cast<::backoff::Exponential*>(value);
  // @@protoc_insertion_point(field_set_allocated:backoff.Backoff.exponential)
}

// .backoff.Constant constant = 3;
inline bool Backoff::has_constant() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.constant_ != nullptr);
  return value;
}
inline void Backoff::clear_constant() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.constant_ != nullptr) _impl_.constant_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::backoff::Constant& Backoff::_internal_constant() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::backoff::Constant* p = _impl_.constant_;
  return p != nullptr ? *p : reinterpret_cast<const ::backoff::Constant&>(::backoff::_Constant_default_instance_);
}
inline const ::backoff::Constant& Backoff::constant() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:backoff.Backoff.constant)
  return _internal_constant();
}
inline void Backoff::unsafe_arena_set_allocated_constant(
    ::backoff::Constant* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.constant_);
  }
  _impl_.constant_ = reinterpret_cast<::backoff::Constant*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:backoff.Backoff.constant)
}
inline ::backoff::Constant* PROTOBUF_NULLABLE Backoff::release_constant() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::backoff::Constant* released = _impl_.constant_;
  _impl_.constant_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::backoff::Constant* PROTOBUF_NULLABLE Backoff::unsafe_arena_release_constant() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:backoff.Backoff.constant)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::backoff::Constant* temp = _impl_.constant_;
  _impl_.constant_ = nullptr;
  return temp;
}
inline ::backoff::Constant* PROTOBUF_NONNULL Backoff::_internal_mutable_constant() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.constant_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::backoff::Constant>(GetArena());
    _impl_.constant_ = reinterpret_cast<::backoff::Constant*>(p);
  }
  return _impl_.constant_;
}
inline ::backoff::Constant* PROTOBUF_NONNULL Backoff::mutable_constant()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::backoff::Constant* _msg = _internal_mutable_constant();
  // @@protoc_insertion_point(field_mutable:backoff.Backoff.constant)
  return _msg;
}
inline void Backoff::set_allocated_constant(::backoff::Constant* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.constant_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.constant_ = reinterpret_cast<::backoff::Constant*>(value);
  // @@protoc_insertion_point(field_set_allocated:backoff.Backoff.constant)
}

// -------------------------------------------------------------------

// Exponential

// uint32 initial_interval = 1;
inline void Exponential::clear_initial_interval() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.initial_interval_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t Exponential::initial_interval() const {
  // @@protoc_insertion_point(field_get:backoff.Exponential.initial_interval)
  return _internal_initial_interval();
}
inline void Exponential::set_initial_interval(::uint32_t value) {
  _internal_set_initial_interval(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:backoff.Exponential.initial_interval)
}
inline ::uint32_t Exponential::_internal_initial_interval() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.initial_interval_;
}
inline void Exponential::_internal_set_initial_interval(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.initial_interval_ = value;
}

// float multiplier = 2;
inline void Exponential::clear_multiplier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.multiplier_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline float Exponential::multiplier() const {
  // @@protoc_insertion_point(field_get:backoff.Exponential.multiplier)
  return _internal_multiplier();
}
inline void Exponential::set_multiplier(float value) {
  _internal_set_multiplier(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:backoff.Exponential.multiplier)
}
inline float Exponential::_internal_multiplier() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.multiplier_;
}
inline void Exponential::_internal_set_multiplier(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.multiplier_ = value;
}

// uint32 max_interval = 3;
inline void Exponential::clear_max_interval() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_interval_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t Exponential::max_interval() const {
  // @@protoc_insertion_point(field_get:backoff.Exponential.max_interval)
  return _internal_max_interval();
}
inline void Exponential::set_max_interval(::uint32_t value) {
  _internal_set_max_interval(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:backoff.Exponential.max_interval)
}
inline ::uint32_t Exponential::_internal_max_interval() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_interval_;
}
inline void Exponential::_internal_set_max_interval(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_interval_ = value;
}

// float randomization_factor = 4;
inline void Exponential::clear_randomization_factor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.randomization_factor_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline float Exponential::randomization_factor() const {
  // @@protoc_insertion_point(field_get:backoff.Exponential.randomization_factor)
  return _internal_randomization_factor();
}
inline void Exponential::set_randomization_factor(float value) {
  _internal_set_randomization_factor(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:backoff.Exponential.randomization_factor)
}
inline float Exponential::_internal_randomization_factor() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.randomization_factor_;
}
inline void Exponential::_internal_set_randomization_factor(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.randomization_factor_ = value;
}

// uint32 max_elapsed_time = 5;
inline void Exponential::clear_max_elapsed_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_elapsed_time_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint32_t Exponential::max_elapsed_time() const {
  // @@protoc_insertion_point(field_get:backoff.Exponential.max_elapsed_time)
  return _internal_max_elapsed_time();
}
inline void Exponential::set_max_elapsed_time(::uint32_t value) {
  _internal_set_max_elapsed_time(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:backoff.Exponential.max_elapsed_time)
}
inline ::uint32_t Exponential::_internal_max_elapsed_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.max_elapsed_time_;
}
inline void Exponential::_internal_set_max_elapsed_time(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.max_elapsed_time_ = value;
}

// -------------------------------------------------------------------

// Constant

// uint32 interval = 1;
inline void Constant::clear_interval() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.interval_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t Constant::interval() const {
  // @@protoc_insertion_point(field_get:backoff.Constant.interval)
  return _internal_interval();
}
inline void Constant::set_interval(::uint32_t value) {
  _internal_set_interval(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:backoff.Constant.interval)
}
inline ::uint32_t Constant::_internal_interval() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.interval_;
}
inline void Constant::_internal_set_interval(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.interval_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace backoff


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::backoff::BackoffKind> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::backoff::BackoffKind>() {
  return ::backoff::BackoffKind_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto_2epb_2eh
