//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/util/backoff/backoff.proto
// Protobuf C++ Version: 6.33.4

#include "backoff.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace backoff {

inline constexpr Exponential::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        initial_interval_{0u},
        multiplier_{0},
        max_interval_{0u},
        randomization_factor_{0},
        max_elapsed_time_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR Exponential::Exponential(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Exponential_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ExponentialDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ExponentialDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ExponentialDefaultTypeInternal() {}
  union {
    Exponential _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ExponentialDefaultTypeInternal _Exponential_default_instance_;

inline constexpr Constant::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        interval_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR Constant::Constant(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Constant_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ConstantDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ConstantDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ConstantDefaultTypeInternal() {}
  union {
    Constant _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ConstantDefaultTypeInternal _Constant_default_instance_;

inline constexpr Backoff::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        exponential_{nullptr},
        constant_{nullptr},
        backoff_kind_{static_cast< ::backoff::BackoffKind >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR Backoff::Backoff(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Backoff_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BackoffDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BackoffDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BackoffDefaultTypeInternal() {}
  union {
    Backoff _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BackoffDefaultTypeInternal _Backoff_default_instance_;
}  // namespace backoff
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto = nullptr;
const ::uint32_t
    TableStruct_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::backoff::Backoff, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::backoff::Backoff, _impl_.backoff_kind_),
        PROTOBUF_FIELD_OFFSET(::backoff::Backoff, _impl_.exponential_),
        PROTOBUF_FIELD_OFFSET(::backoff::Backoff, _impl_.constant_),
        2,
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::backoff::Exponential, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::backoff::Exponential, _impl_.initial_interval_),
        PROTOBUF_FIELD_OFFSET(::backoff::Exponential, _impl_.multiplier_),
        PROTOBUF_FIELD_OFFSET(::backoff::Exponential, _impl_.max_interval_),
        PROTOBUF_FIELD_OFFSET(::backoff::Exponential, _impl_.randomization_factor_),
        PROTOBUF_FIELD_OFFSET(::backoff::Exponential, _impl_.max_elapsed_time_),
        0,
        1,
        2,
        3,
        4,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::backoff::Constant, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::backoff::Constant, _impl_.interval_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::backoff::Backoff)},
        {9, sizeof(::backoff::Exponential)},
        {22, sizeof(::backoff::Constant)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::backoff::_Backoff_default_instance_._instance,
    &::backoff::_Exponential_default_instance_._instance,
    &::backoff::_Constant_default_instance_._instance,
};
const char descriptor_table_protodef_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n6github.com/aperturerobotics/util/backo"
    "ff/backoff.proto\022\007backoff\"\205\001\n\007Backoff\022*\n"
    "\014backoff_kind\030\001 \001(\0162\024.backoff.BackoffKin"
    "d\022)\n\013exponential\030\002 \001(\0132\024.backoff.Exponen"
    "tial\022#\n\010constant\030\003 \001(\0132\021.backoff.Constan"
    "t\"\211\001\n\013Exponential\022\030\n\020initial_interval\030\001 "
    "\001(\r\022\022\n\nmultiplier\030\002 \001(\002\022\024\n\014max_interval\030"
    "\003 \001(\r\022\034\n\024randomization_factor\030\004 \001(\002\022\030\n\020m"
    "ax_elapsed_time\030\005 \001(\r\"\034\n\010Constant\022\020\n\010int"
    "erval\030\001 \001(\r*]\n\013BackoffKind\022\027\n\023BackoffKin"
    "d_UNKNOWN\020\000\022\033\n\027BackoffKind_EXPONENTIAL\020\001"
    "\022\030\n\024BackoffKind_CONSTANT\020\002b\006proto3"
};
static ::absl::once_flag descriptor_table_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto = {
    false,
    false,
    474,
    descriptor_table_protodef_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto,
    "github.com/aperturerobotics/util/backoff/backoff.proto",
    &descriptor_table_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto::offsets,
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto,
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto,
};
namespace backoff {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL BackoffKind_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto);
  return file_level_enum_descriptors_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t BackoffKind_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class Backoff::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Backoff>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Backoff, _impl_._has_bits_);
};

Backoff::Backoff(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Backoff_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:backoff.Backoff)
}
PROTOBUF_NDEBUG_INLINE Backoff::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::backoff::Backoff& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Backoff::Backoff(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Backoff& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Backoff_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Backoff* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.exponential_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.exponential_)
                : nullptr;
  _impl_.constant_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.constant_)
                : nullptr;
  _impl_.backoff_kind_ = from._impl_.backoff_kind_;

  // @@protoc_insertion_point(copy_constructor:backoff.Backoff)
}
PROTOBUF_NDEBUG_INLINE Backoff::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Backoff::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, exponential_),
           0,
           offsetof(Impl_, backoff_kind_) -
               offsetof(Impl_, exponential_) +
               sizeof(Impl_::backoff_kind_));
}
Backoff::~Backoff() {
  // @@protoc_insertion_point(destructor:backoff.Backoff)
  SharedDtor(*this);
}
inline void Backoff::SharedDtor(MessageLite& self) {
  Backoff& this_ = static_cast<Backoff&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.exponential_;
  delete this_._impl_.constant_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Backoff::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Backoff(arena);
}
constexpr auto Backoff::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Backoff),
                                            alignof(Backoff));
}
constexpr auto Backoff::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Backoff_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Backoff::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Backoff>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Backoff::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Backoff>(), &Backoff::ByteSizeLong,
              &Backoff::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Backoff, _impl_._cached_size_),
          false,
      },
      &Backoff::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Backoff_class_data_ =
        Backoff::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Backoff::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Backoff_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Backoff_class_data_.tc_table);
  return Backoff_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2>
Backoff::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Backoff, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Backoff_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::backoff::Backoff>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .backoff.BackoffKind backoff_kind = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Backoff, _impl_.backoff_kind_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(Backoff, _impl_.backoff_kind_)}},
    // .backoff.Exponential exponential = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(Backoff, _impl_.exponential_)}},
    // .backoff.Constant constant = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1,
      PROTOBUF_FIELD_OFFSET(Backoff, _impl_.constant_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .backoff.BackoffKind backoff_kind = 1;
    {PROTOBUF_FIELD_OFFSET(Backoff, _impl_.backoff_kind_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // .backoff.Exponential exponential = 2;
    {PROTOBUF_FIELD_OFFSET(Backoff, _impl_.exponential_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .backoff.Constant constant = 3;
    {PROTOBUF_FIELD_OFFSET(Backoff, _impl_.constant_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::backoff::Exponential>()},
      {::_pbi::TcParser::GetTable<::backoff::Constant>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Backoff::Clear() {
// @@protoc_insertion_point(message_clear_start:backoff.Backoff)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(_impl_.exponential_ != nullptr);
      _impl_.exponential_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.constant_ != nullptr);
      _impl_.constant_->Clear();
    }
  }
  _impl_.backoff_kind_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Backoff::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Backoff& this_ = static_cast<const Backoff&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Backoff::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Backoff& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:backoff.Backoff)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .backoff.BackoffKind backoff_kind = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_backoff_kind() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_backoff_kind(), target);
    }
  }

  // .backoff.Exponential exponential = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.exponential_, this_._impl_.exponential_->GetCachedSize(), target,
        stream);
  }

  // .backoff.Constant constant = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.constant_, this_._impl_.constant_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:backoff.Backoff)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Backoff::ByteSizeLong(const MessageLite& base) {
  const Backoff& this_ = static_cast<const Backoff&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Backoff::ByteSizeLong() const {
  const Backoff& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:backoff.Backoff)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // .backoff.Exponential exponential = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.exponential_);
    }
    // .backoff.Constant constant = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.constant_);
    }
    // .backoff.BackoffKind backoff_kind = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_backoff_kind() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_backoff_kind());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Backoff::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Backoff*>(&to_msg);
  auto& from = static_cast<const Backoff&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:backoff.Backoff)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.exponential_ != nullptr);
      if (_this->_impl_.exponential_ == nullptr) {
        _this->_impl_.exponential_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.exponential_);
      } else {
        _this->_impl_.exponential_->MergeFrom(*from._impl_.exponential_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.constant_ != nullptr);
      if (_this->_impl_.constant_ == nullptr) {
        _this->_impl_.constant_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.constant_);
      } else {
        _this->_impl_.constant_->MergeFrom(*from._impl_.constant_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_backoff_kind() != 0) {
        _this->_impl_.backoff_kind_ = from._impl_.backoff_kind_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Backoff::CopyFrom(const Backoff& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:backoff.Backoff)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Backoff::InternalSwap(Backoff* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Backoff, _impl_.backoff_kind_)
      + sizeof(Backoff::_impl_.backoff_kind_)
      - PROTOBUF_FIELD_OFFSET(Backoff, _impl_.exponential_)>(
          reinterpret_cast<char*>(&_impl_.exponential_),
          reinterpret_cast<char*>(&other->_impl_.exponential_));
}

::google::protobuf::Metadata Backoff::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Exponential::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Exponential>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Exponential, _impl_._has_bits_);
};

Exponential::Exponential(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Exponential_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:backoff.Exponential)
}
Exponential::Exponential(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Exponential& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Exponential_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Exponential::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Exponential::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, initial_interval_),
           0,
           offsetof(Impl_, max_elapsed_time_) -
               offsetof(Impl_, initial_interval_) +
               sizeof(Impl_::max_elapsed_time_));
}
Exponential::~Exponential() {
  // @@protoc_insertion_point(destructor:backoff.Exponential)
  SharedDtor(*this);
}
inline void Exponential::SharedDtor(MessageLite& self) {
  Exponential& this_ = static_cast<Exponential&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Exponential::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Exponential(arena);
}
constexpr auto Exponential::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Exponential),
                                            alignof(Exponential));
}
constexpr auto Exponential::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Exponential_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Exponential::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Exponential>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Exponential::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Exponential>(), &Exponential::ByteSizeLong,
              &Exponential::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Exponential, _impl_._cached_size_),
          false,
      },
      &Exponential::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Exponential_class_data_ =
        Exponential::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Exponential::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Exponential_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Exponential_class_data_.tc_table);
  return Exponential_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2>
Exponential::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Exponential, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Exponential_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::backoff::Exponential>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 initial_interval = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Exponential, _impl_.initial_interval_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(Exponential, _impl_.initial_interval_)}},
    // float multiplier = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0,
      PROTOBUF_FIELD_OFFSET(Exponential, _impl_.multiplier_)}},
    // uint32 max_interval = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Exponential, _impl_.max_interval_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(Exponential, _impl_.max_interval_)}},
    // float randomization_factor = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 3, 0,
      PROTOBUF_FIELD_OFFSET(Exponential, _impl_.randomization_factor_)}},
    // uint32 max_elapsed_time = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Exponential, _impl_.max_elapsed_time_), 4>(),
     {40, 4, 0,
      PROTOBUF_FIELD_OFFSET(Exponential, _impl_.max_elapsed_time_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 initial_interval = 1;
    {PROTOBUF_FIELD_OFFSET(Exponential, _impl_.initial_interval_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // float multiplier = 2;
    {PROTOBUF_FIELD_OFFSET(Exponential, _impl_.multiplier_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // uint32 max_interval = 3;
    {PROTOBUF_FIELD_OFFSET(Exponential, _impl_.max_interval_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // float randomization_factor = 4;
    {PROTOBUF_FIELD_OFFSET(Exponential, _impl_.randomization_factor_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // uint32 max_elapsed_time = 5;
    {PROTOBUF_FIELD_OFFSET(Exponential, _impl_.max_elapsed_time_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Exponential::Clear() {
// @@protoc_insertion_point(message_clear_start:backoff.Exponential)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    ::memset(&_impl_.initial_interval_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.max_elapsed_time_) -
        reinterpret_cast<char*>(&_impl_.initial_interval_)) + sizeof(_impl_.max_elapsed_time_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Exponential::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Exponential& this_ = static_cast<const Exponential&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Exponential::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Exponential& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:backoff.Exponential)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 initial_interval = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_initial_interval() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_initial_interval(), target);
    }
  }

  // float multiplier = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_multiplier()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          2, this_._internal_multiplier(), target);
    }
  }

  // uint32 max_interval = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_max_interval() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_max_interval(), target);
    }
  }

  // float randomization_factor = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_randomization_factor()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          4, this_._internal_randomization_factor(), target);
    }
  }

  // uint32 max_elapsed_time = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_max_elapsed_time() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          5, this_._internal_max_elapsed_time(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:backoff.Exponential)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Exponential::ByteSizeLong(const MessageLite& base) {
  const Exponential& this_ = static_cast<const Exponential&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Exponential::ByteSizeLong() const {
  const Exponential& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:backoff.Exponential)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // uint32 initial_interval = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_initial_interval() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_initial_interval());
      }
    }
    // float multiplier = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_multiplier()) != 0) {
        total_size += 5;
      }
    }
    // uint32 max_interval = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_max_interval() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_max_interval());
      }
    }
    // float randomization_factor = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_randomization_factor()) != 0) {
        total_size += 5;
      }
    }
    // uint32 max_elapsed_time = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_max_elapsed_time() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_max_elapsed_time());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Exponential::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Exponential*>(&to_msg);
  auto& from = static_cast<const Exponential&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:backoff.Exponential)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (from._internal_initial_interval() != 0) {
        _this->_impl_.initial_interval_ = from._impl_.initial_interval_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_multiplier()) != 0) {
        _this->_impl_.multiplier_ = from._impl_.multiplier_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_max_interval() != 0) {
        _this->_impl_.max_interval_ = from._impl_.max_interval_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_randomization_factor()) != 0) {
        _this->_impl_.randomization_factor_ = from._impl_.randomization_factor_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_max_elapsed_time() != 0) {
        _this->_impl_.max_elapsed_time_ = from._impl_.max_elapsed_time_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Exponential::CopyFrom(const Exponential& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:backoff.Exponential)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Exponential::InternalSwap(Exponential* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Exponential, _impl_.max_elapsed_time_)
      + sizeof(Exponential::_impl_.max_elapsed_time_)
      - PROTOBUF_FIELD_OFFSET(Exponential, _impl_.initial_interval_)>(
          reinterpret_cast<char*>(&_impl_.initial_interval_),
          reinterpret_cast<char*>(&other->_impl_.initial_interval_));
}

::google::protobuf::Metadata Exponential::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Constant::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Constant>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Constant, _impl_._has_bits_);
};

Constant::Constant(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Constant_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:backoff.Constant)
}
Constant::Constant(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Constant& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Constant_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Constant::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Constant::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.interval_ = {};
}
Constant::~Constant() {
  // @@protoc_insertion_point(destructor:backoff.Constant)
  SharedDtor(*this);
}
inline void Constant::SharedDtor(MessageLite& self) {
  Constant& this_ = static_cast<Constant&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Constant::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Constant(arena);
}
constexpr auto Constant::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Constant),
                                            alignof(Constant));
}
constexpr auto Constant::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Constant_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Constant::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Constant>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Constant::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Constant>(), &Constant::ByteSizeLong,
              &Constant::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Constant, _impl_._cached_size_),
          false,
      },
      &Constant::kDescriptorMethods,
      &descriptor_table_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Constant_class_data_ =
        Constant::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Constant::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Constant_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Constant_class_data_.tc_table);
  return Constant_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
Constant::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Constant, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Constant_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::backoff::Constant>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 interval = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Constant, _impl_.interval_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(Constant, _impl_.interval_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 interval = 1;
    {PROTOBUF_FIELD_OFFSET(Constant, _impl_.interval_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Constant::Clear() {
// @@protoc_insertion_point(message_clear_start:backoff.Constant)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.interval_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Constant::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Constant& this_ = static_cast<const Constant&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Constant::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Constant& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:backoff.Constant)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint32 interval = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_interval() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_interval(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:backoff.Constant)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Constant::ByteSizeLong(const MessageLite& base) {
  const Constant& this_ = static_cast<const Constant&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Constant::ByteSizeLong() const {
  const Constant& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:backoff.Constant)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // uint32 interval = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_interval() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_interval());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Constant::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Constant*>(&to_msg);
  auto& from = static_cast<const Constant&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:backoff.Constant)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_interval() != 0) {
      _this->_impl_.interval_ = from._impl_.interval_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Constant::CopyFrom(const Constant& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:backoff.Constant)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Constant::InternalSwap(Constant* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.interval_, other->_impl_.interval_);
}

::google::protobuf::Metadata Constant::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace backoff
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2futil_2fbackoff_2fbackoff_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
