//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/util/enabled/enabled.proto
// Protobuf C++ Version: 6.33.4

#include "enabled.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace enabled {
}  // namespace enabled
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto = nullptr;
const ::uint32_t TableStruct_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* PROTOBUF_NULLABLE schemas = nullptr;
static constexpr ::_pb::Message* PROTOBUF_NONNULL const* PROTOBUF_NULLABLE
    file_default_instances = nullptr;
const char descriptor_table_protodef_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n6github.com/aperturerobotics/util/enabl"
    "ed/enabled.proto\022\007enabled*/\n\007Enabled\022\013\n\007"
    "DEFAULT\020\000\022\n\n\006ENABLE\020\001\022\013\n\007DISABLE\020\002b\006prot"
    "o3"
};
static ::absl::once_flag descriptor_table_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto = {
    false,
    false,
    122,
    descriptor_table_protodef_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto,
    "github.com/aperturerobotics/util/enabled/enabled.proto",
    &descriptor_table_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto::offsets,
    file_level_enum_descriptors_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto,
    file_level_service_descriptors_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto,
};
namespace enabled {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Enabled_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto);
  return file_level_enum_descriptors_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Enabled_internal_data_[] = {
    196608u, 0u, };
// @@protoc_insertion_point(namespace_scope)
}  // namespace enabled
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
