// @generated
// This file is @generated by prost-build.
/// Enabled is a three-way boolean: default, enable, disable.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Enabled {
    /// DEFAULT defaults to the default option.
    Default = 0,
    /// ENABLE enables the option even if it would normally be false.
    Enable = 1,
    /// DISABLE disables the option even if it would normally be true.
    Disable = 2,
}
impl Enabled {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Default => "DEFAULT",
            Self::Enable => "ENABLE",
            Self::Disable => "DISABLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DEFAULT" => Some(Self::Default),
            "ENABLE" => Some(Self::Enable),
            "DISABLE" => Some(Self::Disable),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
