// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/util/enabled/enabled.proto (package enabled, syntax proto3)
/* eslint-disable */

import { createEnumType } from '@aptre/protobuf-es-lite'

export const protobufPackage = 'enabled'

/**
 * Enabled is a three-way boolean: default, enable, disable.
 *
 * @generated from enum enabled.Enabled
 */
export enum Enabled {
  /**
   * DEFAULT defaults to the default option.
   *
   * @generated from enum value: DEFAULT = 0;
   */
  DEFAULT = 0,

  /**
   * ENABLE enables the option even if it would normally be false.
   *
   * @generated from enum value: ENABLE = 1;
   */
  ENABLE = 1,

  /**
   * DISABLE disables the option even if it would normally be true.
   *
   * @generated from enum value: DISABLE = 2;
   */
  DISABLE = 2,
}

// Enabled_Enum is the enum type for Enabled.
export const Enabled_Enum = createEnumType('enabled.Enabled', [
  { no: 0, name: 'DEFAULT' },
  { no: 1, name: 'ENABLE' },
  { no: 2, name: 'DISABLE' },
])
