//go:build deps_only && cgo

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: github.com/aperturerobotics/util/enabled/enabled.proto
// Protobuf C++ Version: 6.33.4

#ifndef github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto_2epb_2eh
#define github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto;
}  // extern "C"
namespace enabled {
enum Enabled : int;
extern const uint32_t Enabled_internal_data_[];
}  // namespace enabled
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::enabled::Enabled_internal_data_>
    internal::EnumTraitsImpl::value<::enabled::Enabled>;
}  // namespace protobuf
}  // namespace google

namespace enabled {
enum Enabled : int {
  DEFAULT = 0,
  ENABLE = 1,
  DISABLE = 2,
  Enabled_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Enabled_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Enabled_internal_data_[];
inline constexpr Enabled Enabled_MIN =
    static_cast<Enabled>(0);
inline constexpr Enabled Enabled_MAX =
    static_cast<Enabled>(2);
inline bool Enabled_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int Enabled_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Enabled_descriptor();
template <typename T>
const ::std::string& Enabled_Name(T value) {
  static_assert(::std::is_same<T, Enabled>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Enabled_Name().");
  return Enabled_Name(static_cast<Enabled>(value));
}
template <>
inline const ::std::string& Enabled_Name(Enabled value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Enabled_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool Enabled_Parse(
    ::absl::string_view name, Enabled* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Enabled>(Enabled_descriptor(), name,
                                           value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace enabled


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::enabled::Enabled> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::enabled::Enabled>() {
  return ::enabled::Enabled_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // github_2ecom_2faperturerobotics_2futil_2fenabled_2fenabled_2eproto_2epb_2eh
